const express = require("express");
const PDFDocument = require("pdfkit");
const { protect, authorize } = require("../middlewares/authMiddleware");
const Submission = require("../models/Submission");
const s3 = require("../config/s3");
const axios = require("axios");

const router = express.Router();

router.post("/submissions/:id/report", protect, authorize("admin"), async (req, res) => {
  try {
    const submission = await Submission.findById(req.params.id).populate("patient", "name email");
    if (!submission) return res.status(404).json({ message: "Submission not found" });

    let originalImgBuffer = null;
    let annotatedImgBuffer = null;

    if (submission.originalImageUrl) {
      const key = decodeURIComponent(new URL(submission.originalImageUrl).pathname.substring(1));
      const s3Object = await s3.getObject({ Bucket: process.env.AWS_BUCKET_NAME, Key: key }).promise();
      originalImgBuffer = s3Object.Body;
    }

    if (submission.annotatedImageUrl) {
      const key = decodeURIComponent(new URL(submission.annotatedImageUrl).pathname.substring(1));
      const s3Object = await s3.getObject({ Bucket: process.env.AWS_BUCKET_NAME, Key: key }).promise();
      annotatedImgBuffer = s3Object.Body;
    }


    const ANNOTATION_TYPES = [
      { type: "Caries", color: "#e11d48" },
      { type: "Stains", color: "#f59e42" },
      { type: "Scaling", color: "#2563eb" },
    ];

  const doc = new PDFDocument({ margin: 50, size: 'A4' });
    let buffers = [];
    doc.on("data", buffers.push.bind(buffers));

    const pdfEndPromise = new Promise((resolve, reject) => {
      doc.on("end", resolve);
      doc.on("error", reject);
    });

    doc.save();
    doc.rect(0, 0, doc.page.width, 60).fill("#2563eb");
    doc.fillColor("white").fontSize(28).font("Helvetica-Bold").text("OralVis Patient Report", 0, 18, { align: "center", width: doc.page.width });
    doc.restore();
    doc.moveDown(2);

    const contentWidth = 380;
    const contentX = (doc.page.width - contentWidth) / 2;

    doc.fontSize(14).fillColor("#22223b").font("Helvetica-Bold").text("Patient Information", contentX, doc.y, { underline: true, width: contentWidth, align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(12).fillColor("black").font("Helvetica");
    doc.text(`Name: ${submission.patient.name}`, contentX, doc.y, { width: contentWidth, align: "center" });
    doc.text(`Email: ${submission.email}`, contentX, doc.y, { width: contentWidth, align: "center" });
    doc.text(`Note: ${submission.note}`, contentX, doc.y, { width: contentWidth, align: "center" });
    doc.text(`Uploaded: ${submission.createdAt.toLocaleString()}`, contentX, doc.y, { width: contentWidth, align: "center" });
    doc.moveDown();

    doc.moveTo(contentX, doc.y).lineTo(contentX + contentWidth, doc.y).strokeColor("#2563eb").lineWidth(1).stroke();
    doc.moveDown(1.2);

    doc.fontSize(14).fillColor("#22223b").font("Helvetica-Bold").text("Annotated Image", contentX, doc.y, { underline: true, width: contentWidth, align: "center" });
    doc.moveDown(0.5);
    let afterImageY = doc.y;
    if (annotatedImgBuffer) {
      doc.image(annotatedImgBuffer, contentX + 10, doc.y, { fit: [contentWidth - 20, 180], align: "center" });
      afterImageY = doc.y + 180 + 10; // 180 is fit height, 10 is spacing
      doc.y = afterImageY;
      doc.moveDown(0.5);
    } else {
      doc.fontSize(12).fillColor("#e11d48").text("Annotated image not available.", contentX, doc.y, { width: contentWidth, align: "center" });
      doc.moveDown(1);
    }

    doc.fontSize(14).fillColor('#22223b').font("Helvetica-Bold").text("Annotation Key", contentX, doc.y, { underline: true, width: contentWidth, align: "center" });
    doc.moveDown(0.5);
    let keyY = doc.y;
    const boxSize = 16;
    const rowSpacing = 10;
    ANNOTATION_TYPES.forEach((t, idx) => {
      const rowX = contentX + 30;
      doc.rect(rowX, keyY, boxSize, boxSize).fillAndStroke(t.color, t.color).stroke();
      doc.fillColor("black").font("Helvetica").fontSize(12).text(
        t.type,
        rowX + boxSize + 8,
        keyY + 2,
        { continued: false }
      );
      keyY += boxSize + rowSpacing;
    });
    doc.y = keyY + 10;
    doc.moveDown(1);

    const footerY = doc.page.height - doc.page.margins.bottom - 25;
    doc.fontSize(10).fillColor("#888").text("Generated by OralVis | Confidential", 0, footerY, { align: "center", width: doc.page.width });

    doc.end();
    await pdfEndPromise;

    const pdfBuffer = Buffer.concat(buffers);

    const s3Params = {
      Bucket: process.env.AWS_BUCKET_NAME,
      Key: `reports/${Date.now()}-${submission.patientId}.pdf`,
      Body: pdfBuffer,
      ContentType: "application/pdf",
    };

    const s3Data = await s3.upload(s3Params).promise();

    submission.reportUrl = s3Data.Location;
    submission.status = "reported";
    submission.updatedAt = Date.now();
    await submission.save();

    res.json({ message: "Report generated successfully", reportUrl: s3Data.Location });
  } catch (err) {
    console.error(err);
    res.status(500).json({ message: "Failed to generate report" });
  }
});

module.exports = router;